name: DME Build Common

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MS_TEAMS_WEBHOOK_URI:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repo: sunteck/dme-app
            target: app
          - repo: sunteck/dme-web
            target: web
    env:
      GIT_REF: ${{ inputs.ref }}
      IMAGE_TAG: ${{ inputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_REF }}

      - name: Output Input and Env
        run: |
          echo inputs.ref ${{ inputs.ref }}
          echo env.GIT_REF ${{ env.GIT_REF }}
          echo inputs.image_tag ${{ inputs.image_tag }}
          echo env.IMAGE_TAG ${{ env.IMAGE_TAG }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ matrix.repo }}
          TARGET: ${{ matrix.target }}
        with:
          context: .
          target: ${{ env.TARGET }}
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-to: type=inline

  notify-team-start:
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify Start
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Digital Matching Engine ${{ github.event.inputs.ref || inputs.ref }} build (${{ github.actor }}): Started..."
          notification-color: 28a745

  notify-team-success:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Success
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Digital Matching Engine ${{ github.event.inputs.ref || inputs.ref }} build (${{ github.actor }}) completed successfully. Image was pushed to ECR and is available to be deployed. :white_check_mark:"
          notification-color: 33ff66

  notify-team-failure:
    if: failure()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Failure
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Digital Matching Engine ${{ github.event.inputs.ref || inputs.ref }} build (${{ github.actor }}): Failure :o:"
          notification-color: ff0000