name: Carrier Portal Prod Build

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/carriers-*.yml'
      - 'carriers/**'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: true
        default: 'master'

jobs:
  test:
    uses: ./.github/workflows/carriers-test.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build:
    needs: [test]
    uses: ./.github/workflows/carriers-build.yml
    with:
      ref: master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

  notify-team-start:
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify Start
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Carrier Portal (${{ github.ref }}) QA/Tests: Started..."
          notification-color: 28a745

  notify-team-success:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Success
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Carrier Portal (${{ github.ref }}) QA/Tests: Success :white_check_mark:"
          notification-color: 33ff66

  notify-team-failure:
    if: ${{ failure() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Failure
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Carrier Portal (${{ github.ref }}) QA/Tests: Failure :o:"
          notification-color: ff0000
