name: BTMS Deploy Widgets Common

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      app_env:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MS_TEAMS_WEBHOOK_URI:
        required: true
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, sha) to deploy"
        required: true
        type: string
      app_env:
        description: "Application environment (qc, stage, production)"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ inputs.app_env }}
      NODE_VERSION: 14
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and deploy widgets
        env:
          CI: false
        run: |
          cd btms/widgets/
          npm install --no-bin-links
          npm run build:${{ env.APP_ENV }}
          aws s3 cp ./build/fats/assets/widgets s3://sunteck-assets/btms/${{ env.APP_ENV }}/widgets/ --recursive --acl public-read --cache-control "max-age=0,no-cache,no-store,must-revalidate"
  notify-team-failure:
    #if: failure()
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams Deploy Card
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
#         with:
#           github-token: ${{ github.token }}
#           ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
#           notification-summary: "BTMS Deploy ${{ inputs.app_env }} Widgets ${{ inputs.ref }} Failure (ONLY Failure are Notified)"
#           notification-color: ff0000
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: US/Eastern
        
