name: Tracking Portal Test

on:
  pull_request:
    paths:
      - '.github/workflows/tracking-test.yml'
      - 'tracking/**'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: true
        default: 'develop'
  workflow_call:
    secrets:
      MS_TEAMS_WEBHOOK_URI:
        required: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8
          tools: parallel-lint, cs2pr, composer
      - name: Lint PHP code
        run: parallel-lint --checkstyle ./tracking | cs2pr
      - name: Get composer cache directory
        id: composer-cache
        working-directory: ./tracking
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        working-directory: ./tracking
        run: composer install --prefer-dist
      - name: Detect coding standard violations
        continue-on-error: true
        run: ./tracking/vendor/bin/phpcs --standard=./tracking/phpcs.xml.dist -p --basepath=. --report-full --report-checkstyle=./phpcs-report.xml
      - name: Show PHPCS results in PR
        run: cs2pr --graceful-warnings ./phpcs-report.xml
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No test required"'

  notify-team-start:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify Start
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Tracking Portal (${{ github.ref }}) QA/Tests: Started...'
          color: 'info'

  notify-team-success:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [static-analysis, test]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Success
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Tracking Portal (${{ github.ref }}) QA/Tests: Success :white_check_mark:'
          color: 'success'

  notify-team-failure:
    if: ${{ failure() && github.event_name != 'pull_request' }}
    needs: [static-analysis, test]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Failure
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Tracking Portal (${{ github.ref }}) QA/Tests: Failure :o:'
          color: 'failure'
