name: Carrier Portal QC Deploy

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/carriers-*.yml'
      - 'carriers/**'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref'
        required: true
        default: 'develop'

jobs:
  test:
    uses: ./.github/workflows/carriers-test.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build:
    needs: [test]
    uses: ./.github/workflows/carriers-build.yml
    with:
      ref: develop
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

  deploy:
    needs: [build]
    uses: ./.github/workflows/carriers-deploy.yml
    with:
      ref: develop
      app_env: qc
      target: 10.1.0.14 # replace with secret ex: ${{ secrets.envHOST }}
      bastion: bastion.qc.modetrans.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

  notify-team-start:
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify Start
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Carrier Portal (${{ github.ref }}) QA/Tests: Started...'
          color: 'info'

  notify-team-success:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Success
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Carrier Portal (${{ github.ref }}) QA/Tests: Success :white_check_mark:'
          color: 'success'

  notify-team-failure:
    if: ${{ failure() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Team Notify of Failure
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          deploy-card: true
          title: 'Carrier Portal (${{ github.ref }}) QA/Tests: Failure :o:'
          color: 'failure'
